# Generated by Django 3.2.6 on 2021-08-04 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('coupon', models.ManyToManyField(null=True, to='coupons.Coupon')),
                ('recommender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
